### ISSUE TITLE
Prophesize method in controller test

### ISSUE THREAD

**Issue by janmaennig** [IchHabRecht/TYPO3-ext_testing#1]
Hi IchHabRecht,

how can i use the "prophesize()" to see in your controller test? In can't find this method in extend test case.

best regards
Jan

**Comment by IchHabRecht** [comment]
Hi Jan,

Prophecies are coming from PHPUnit but not from the TYPO3 core. You can find more information in the [PHPUnit manual](https://phpunit.de/manual/current/en/test-doubles.html#test-doubles.prophecy) and the [GitHub repo](https://github.com/phpspec/prophecy)

**Comment by janmaennig** [comment]
Thanks IchHabRecht, i must have  overlooked this.
